books/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'books'
urlpatterns = [
    path('', views.index, name = 'index'),
    #Home Page
    path('home/' ,views.home, name = 'home'),
    #Search page
    path('search_book/' ,views.search_book, name = 'search_book'),
    #Borrow page
    path('borrow/<int:book_id>' ,views.borrow, name = 'borrow'),
    #Profile page
    path('profile/', views.profile, name = 'profile'),
    #Borrowed book page in the profile
    path('borrowed_book/', views.borrowed_book, name = 'borrowed_book'),
    #Returned book page in the profile
    path('returned_book/', views.returned_book, name = 'returned_book'),
    #Notifications book page in the profile
    path('notifications/', views.notifications, name = 'notifications'),
    #Fines page
    path('fines', views.fines, name = 'fines'),
    #Confirm borrow page
    path('confirm_borrow/<int:id>', views.confirm_borrow, name = 'confirm_borrow'),
    
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #Admin site urls
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    #Users in the django admin site
    path('users/', include('users.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
#write the urls here
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users.forms import LoginForm
from . import views
from django.contrib.auth.views import LoginView
app_name = 'users'
urlpatterns = [
    #login and register Page
    path('', include('django.contrib.auth.urls')),
    #Login page urls for the webapp
    path('login/', LoginView.as_view(authentication_form = LoginForm), name = 'login'),
    #Logged out page urls for the webapp
    path("logged_out/", views.logged_out, name ='logged_out'),
    #Register page urls for the webapp
    path("register/", views.register, name = 'register'),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import CharField
from datetime import *
from django.contrib.auth.models import User

# Create your models here.
"""Model that stores the library books"""
class Book(models.Model):
  CATEGORY = [
    ('education', 'Education'),
    ('comics', 'Comics'),
    ('biography', 'Biography'),
    ('history', 'History'),
    ('novel', 'Novel'),
    ('fantasy', 'Fantasy'),
    ('thriller', 'Thriller'),
    ('romance', 'Romance'),
    ('scifi','Sci-Fi')
  ]
  
  title = models.CharField(max_length=200)
  author = models.CharField(max_length=200)
  category = models.CharField(max_length=40, choices = CATEGORY)
  status = models.BooleanField(default = True)
  description = models.TextField(max_length=3000)
  image = models.ImageField(upload_to = 'pics', blank = True)
  class Meta:
    verbose_name_plural = 'books'


  def __str__(self):
    return self.title

"""Model for the Users borrowing books"""
class Borrower(models.Model):
  first_name = models.CharField(max_length=300)
  last_name = models.CharField(max_length=300)
  username = models.CharField(max_length=300)
  book_name = models.CharField(max_length=300)
  reg_no = models.CharField(max_length=200)
  class Meta:
    verbose_name_plural = 'borrowers'

  def __str__(self):
    return str(self.username)+"["+str(self.book_name)+']'

"""Function to define the return date of the book"""
def get_return_date():
  return datetime.now() + timedelta(hours = 1)

"""Function to define the amount of time for the user to pick the book"""
def book_time_limit():
  return datetime.now() + timedelta(hours=6) 

"""Model for the books issued to a borrower"""
class IssuedBook(models.Model):
  book_name = models.ForeignKey(Book, null = True , on_delete=models.CASCADE)
  borrower = models.ForeignKey(Borrower, null = True , on_delete=models.CASCADE)
  reg_no = models.CharField(max_length=200)
  issued_date = models.DateField(auto_now = True)
  return_date = models.DateField(auto_now = True) 
  class Meta:
    verbose_name_plural = 'issuedbooks'

  def __str__(self):
    return str(self.book_name)+ ' ' +'[' + str(self.borrower) + ']' 


"""Model for the  book requested by the borrower"""
class RequestedBook(models.Model):
  # book_request = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='requested_book_num')
  book_name = models.CharField(max_length= 200)
  return_date = models.DateField(default=get_return_date)
  pickup_time = models.DateTimeField(default=book_time_limit)
  borrower = models.CharField(max_length= 200)
  class Meta:
    verbose_name_plural = 'requestedbooks'

  def __str__(self):
    return str(self.book_name) + '(' + str(self.borrower) + ')'

  # def number_of_requested_books(self):
  #   if self.book_request.count() < 3:
  #     return self.book_request.count()
  #   else:
  #     return "Unable to borrow more than two books."

  


class Returned_book(models.Model):
  borrower = models.ForeignKey(Borrower,on_delete= models.CASCADE)
  book_name = models.ForeignKey(IssuedBook,on_delete= models.CASCADE)
  date_of_return = models.DateTimeField(auto_now = True)
  reg_no = models.BigIntegerField()
  user = models.ForeignKey(User,on_delete= models.CASCADE)
  return_date = models.DateField(auto_now = True)

  # def __str__(self):
  #   return self.book_name + '[' + self.borrower + ']'
  def __str__(self):
    return self.user


  

  

books/views.py
from django.shortcuts import render,redirect
from . import models
from .models import Book
from django.contrib.auth.decorators import login_required
from .models import *
from datetime import *
from django.urls import reverse

# Create your views here.
"""Views for the very first page of the library system"""
def index(request):
    return render(request, 'books/index.html')

"""Defining views for the home page"""
@login_required
def home(request):
    books = Book.objects.all()
    context = {'books':books}
    return render(request, 'books/home.html', context)

"""Defining views for the search_book page"""
@login_required
def search_book(request):
    if request.method == "POST":
        searched = request.POST['searched']
        books = Book.objects.filter(title__icontains=searched)
        context = { 'searched':searched,'books':books }

        return render(request, 'books/search_book.html', context)
    else:
        return render(request, 'books/search_book.html')

"""Defining views for the borrow page"""
@login_required
def borrow(request, book_id):
    clicked = Book.objects.get(id = book_id)
    all_books = Book.objects.all()
    books = Book.objects.filter(title__icontains=clicked)
    context = { 'clicked':clicked, 'books':books, 'all_books':all_books }

    return render(request, 'books/borrow.html', context)

def get_return_date():
  return datetime.now() + timedelta(hours = 1)

def book_time_limit():
  return datetime.now() + timedelta(hours=6)

"""Views for the confirm borrow"""
@login_required
def confirm_borrow(request,id):
    book = Book.objects.get(id=id)
    borrower = Borrower(first_name=request.user.first_name,last_name=request.user.last_name,username=request.user.username,book_name=book.title)
    borrower.save()
 
    requested_book = RequestedBook(book_name = book.title ,pickup_time = book_time_limit(),return_date= get_return_date(),borrower=request.user)
    requested_book.save()
    # notifications = Returned_book
    book.status = False
    book.save()

    context = { 'return_date':requested_book.return_date }

    return render(request, 'books/borrow.html', context)

    # return redirect('books:home')



"""Defining views for the profile page"""
@login_required
def profile(request):
    return render(request, 'books/profile.html')

"""Views for the borrowed book"""
@login_required
def borrowed_book(request):
    requested_book = models.RequestedBook.objects.all()
    li = []
    for book in requested_book:
        issuedate = str(book.issued_date.day)+'-'+str(book.issued_date.month)+'-'+str(book.issued_date.year)
        return_date = str(book.return_date.day)+'-'+str(book.return_date.month)+'-'+str(book.return_date.year)

        books = list(models.Book.objects.filter(book_num = book.book_num))
        students = list(models.Borrower.objects.filter(reg_no = book.reg_no))
        i = 0
        for li in books:
            t = (students[i].get_name, students[i].reg_no, books[i].name, books[i].author, issuedate, return_date)
            i += 1
            li.append(t)
        
    return render(request, 'books/borrowed_book.html')
    

"""Views for the returned book"""
@login_required
def returned_book(request):
    return render(request, 'books/returned_book.html')

"""Views for notifications"""
@login_required
def notifications(request):

    # user = User.objects.all()
    # guy = User.objects.get(username = request.user.username)
    # user = User.objects.all()
    notice = Returned_book.objects.filter(user = request.user)

    if request.user in notice:

        if notice.date_of_retun > notice.return_date + timedelta(hours=2):
            context = {'fine5000': 'you have a fine of 5000 UGX'}
            return render(request,'books/notifications.html',context)
        elif notice.date_of_retun > notice.return_date + timedelta(days=10):
            context = {'fine15000':'you have a fine of 15000 UGX '}
            return render(request,'books/notifications.html',context)
        elif notice.date_of_retun < notice.return_date + timedelta(days=3):
            context = {'nofine':' you dont have any fines'}
            return render(request,'books/notifications.html',context)
        else:
            context = {'nofine':' has entered  the if but doesnt match any of the entries'}
            return render(request,'books/notifications.html',context)
            
    else:
        context = {'nofine':' you dont have any fines'}
        return render(request,'books/notifications.html',context)



    















@login_required
def fines(request):
    if request.method == 'POST':
        pass


    else:
        pass
    
    return render(request, 'books/fines.html')

def borrowed_book(request):
    borrowed = Borrower.objects.all()
    context = {'borrowed':borrowed}
    return render(request,'books/borrowed_book.html', context)

templates/books/borrow.html
{% include 'books/hamburger.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href='{% static "css/style.css" %}'>
    <link rel="stylesheet" href='{% static "css/menu.css" %}'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Titillium+Web:wght@600&display=swap" rel="stylesheet">
    <title>BORROW</title>
</head>

{% block content %}
<body class="mt-5" style="background-image: url('{% static "img/lib4.JPG" %}')"  no-repeat center center-cover;>
    {% for b in books %}
        <div class="container align-text-bottom">
            <div class="media">
                <div class="row">
                    <div class="col col-xs-12 col-md-4">
                        <div class="card">
                            <img class="card-img" src="{{b.image.url}}" alt="bookcover" class="img-responsive" />
                        </div>
                    </div>
                    <div class="col col-xs-10 col-md-8">
                        <div class="card-transparent">
                            <div class="card-body">
                                <p><u><h3 class="text-warning text-responsive"> {{ b }} </h3></u></p>
                                <p class="text-white text-justify"> {{ b.description }} </p>
                                <br>
                                <br>
                                <div>
                                    <span class="font-weight-bold text-warning">Author:</span>
                                    <i class="text-white"> {{ b.author }} </i>
                                </div>
                                <br>
                                <div>
                                    <span class="font-weight-bold text-warning">Genre:</span>
                                    <i class="text-white"> {{ b.category }} </i>
                                </div>
                                <br>
                                <p><u><h5 class="text-warning">Related books</h5></u></p>
                                <ol class="text-white text-monospace">
                                    {% for book in all_books %}
                                        {% if book.category == b.category and book != b %}
                                            <li>{{ book }}</li>
                                        {% endif %}
                                    {% endfor %}
                                </ol>
                                <br>
                                {% if b.status %}
                                    
                                    <p> The book should be picked within 6 hours </p>
                                    <p> Return date : {{ return_date }}</p>
                                    <p class="text-warning"> Status : <span class="text-success">Available</span>  </p>
                            
                                    <a href="{% url 'books:confirm_borrow' b.id %}">{{ b }}
                                        <button class="btn mb-3 btn-outline-warning float-right btn-lg border rounded">BORROW</button>
                                    <!-- the button was put inside the href link , why!! -->
                                    </a>
                                {% else %}
                                    <p class="text-warning"> Status : <span class="text-danger">Unavailable </span> </p>
                                    <button class="btn mb-3 btn-outline-warning float-right btn-lg border rounded disabled" data-toggle="modal" data-target="#modalCenter" type="button">
                                        BORROW
                                    </button>
                            
                                    <div class="modal fade" id="modalCenter" tabindex="-1" role="dialog" aria-labelledby="modalCenterTitle" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                          <div class="modal-content">
                                            <div class="modal-header">
                                              <h5 class="modal-title text-danger text-center" id="modalLongTitle">NOTICE!!</h5>
                                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                              </button>
                                            </div>
                                            <div class="modal-body">
                                              <p>Unfortunately the book has been borrowed. You will have to wait till the the book is returned.</p>
                                            </div>
                                            <div class="modal-footer">
                                              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            </div>
                                          </div>
                                        </div>
                                    </div>
                                {% endif %}
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

    
<script src='{% static "https://code.jquery.com/jquery-3.3.1.slim.min.js"%}' integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
crossorigin="anonymous"></script>
<script src='{% static "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"%}' integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
crossorigin="anonymous"></script>
<script src='{% static "https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"%}' integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
crossorigin="anonymous"></script> 

</body>
</html>

{% endblock content %}

templates/books/borrowed_book.html
{% include 'books/profile.html' %}
<h1 class = "display-6 text-center">Borrowed Books</h1>
    {% for book in issued_book %}
        <p>{{book.book_name}}</p>
    {% endfor %}

templates/books/hamburger.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href='{% static "css/style.css" %}'>
    <link rel="stylesheet" href='{% static "css/menu.css" %}'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Titillium+Web:wght@600&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The Book Library</title>
</head>
<body>
    <div class="menu-wrap">
        <input type="checkbox" class="toggler">
        <div class="hamburger"><div></div></div>
        <div class="menu">
            <div>
                <div>
                    <ul>
                        {% if user.is_authenticated %}
                            <h1 class = "text-warning">Hello, <span class="text-white">{{ user }}</span></h1>
                            <li><a class = "text_secondary" href="{% url 'books:home' %}">Home</a></li>
                            <li><a href="{% url 'users:logout' %}">Logout</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    {% block content %}
    
    
    {% endblock content%}
</body>

templates/books/home.html
{% include 'books/main.html' %}
{% load static %}
{% static "images" as BaseUrl %}
<body>
    {% block content %}
    <div
class="jumbotron jumbotron-fluid text-center"
style="background:url(https://content.codecademy.com/courses/learn-bootstrap-4/adhoc/jumbotron.png) no-repeat center center/cover"
    >
        <div class="text-white p-5">
            <h1 class="display-6"> <span class="text-warning">Welcome<br></span> to The Book Library</h1>
            <p><small>Which book are you interested in?</small></p>
        </div>
    </div>

    <form class="form-inline my-2 my-lg-0 justify-content-center " method=POST action="{% url 'books:search_book' %}">

        {% csrf_token %}
        <input class="form-control mr-2" type="search py-3" placeholder="Search for a Book" name="searched">
        <button class = "btn btn-sm btn-warning" type="submit" >Search</button>
    </form>
    <div class = "container">
        <div class = "container card">
            {% for book in books %}
            <div class="card">
                <div class="row">
                    <div class="col col-xs-10 col-md-8 col-lg-4">
                        <img src="{{book.image.url}}" width="100%" height="auto">
                    </div>
                    <div class="col ">
                        <div class="card-body">
                            <h2 class="text-warning"><a href="{% url 'books:borrow' book.id %}"> {{ book }} </a> <br></h2>
                            <p class="text-responsive">{{ book.description }}</p> <br>
                            <div class="float-right">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <section class = "container clear-fix">
            <div class = "mx-auto text-center">
                <h3>Featured Books</h3>
                <div class = "row mb-3">
                    <!--<img class = "float-left" src='{% static "img\51mPB2812SL._SX382_BO1,204,203,200_.jpg" %}' alt="Modern Statistics">-->
                    <!--<img class = "float-left" src='{% static "img\book.png" %}' alt="Quantum Mechanics">-->
        </section>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
        //Get the current year for the copyright
        $('#year').text(new Date().getFullYear());
    </script>
    {% endblock content %}
</body>

templates/books/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href='{% static "css/style.css" %}'>
    <link rel="stylesheet" href='{% static "css/menu.css" %}'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Titillium+Web:wght@600&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Library Management System</title>
    <style>
        a{
            text-decoration: none;
            color:orange;
        }
        h6{
            font-size: 18px;
            transition: all 0.4s ease-in-out;
        }
    </style>
</head>
<body>
   <header id="showcase">
       <div class="showcase-container container">
           <h1 class = "text_secondary" >The</h1>
           <h1> Book</h1>
           <h1>Library</h1>
           <p>All your favorites in one place.</p>
           <a href="{% url 'users:login' %}"class="btn">Login</a>
           <h6><small>Hello!, Not yet registered?</small></h6>
           <h6><small>Please get registered here:   <span class="text-warning"><a href="{% url 'users:register' %}">Register</a></span></small></h6>
       </div>
   </header>
</body>
</html>

templates/books/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href='{% static "css/style.css" %}'>
    <link rel="stylesheet" href='{% static "css/menu.css" %}'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Titillium+Web:wght@600&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The Book Library</title>
</head>
<body>
  <nav class="navbar mb-auto navbar-expand-lg navbar-dark bg-dark fixed-top mb-2 border">
		<a class="navbar-brand border-md-right" href="home">
			<h4 class=" display-6 text-warning">TBL</h4>
		</a>
		<div class = "ml-auto">
			<h4 class = "display-6 text-warning">Hello, <span class="text-white"> {{ user }} </span></h4>
		</div>
		<div class="ml-auto">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<a class="nav-link active text-warning" href="{% url 'books:profile' %}">Profile</a>
				</li>
			</ul>
		</div>
	</nav>
	{% block content %}
	
	{% endblock %}
</body>
</html>

templates/books/notifications.html
{% include 'books/profile.html' %}
<div>
    {{fine5000}}
    {{fine5000 }}
    {{nofine}}
</div>

templates/books/profile.html
{% include 'books/hamburger.html' %}
{% load static %}
{% block page_header %}
  <div class="container text-center">
    <h1 class = "display-3 text-warning">Your Profile</h1>
    <h2>{{ user }}</h2>
  </div>

  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb" class="text-center">
    <ul class="breadcrumb bg-light text-center ml-auto">
      <li class="breadcrumb-item"><a href="{% url 'books:borrowed_book' %}">Borrowed Books</a></li>
      <li class="breadcrumb-item"><a href="{% url 'books:returned_book' %}">Returned Books</a></li>
      <li class="breadcrumb-item"><a href="{% url 'books:notifications' %}">Notifications</a></li>
    </ul>
  </nav>
{% endblock page_header %}

{% block content %}

{%  endblock content %}

templates/books/returned_book.html
{% include 'books/profile.html' %}

templates/books/search_book.html
{% include 'books/main.html' %}
<br>
<br>
{% block content %}
    {% if searched not in books %}
        <h1 class="text-center">You searched for "{{ searched }}"</h1><br>
        {% for book in books %}
            <div class="card">
                <div class="row">
                    <div class="col col-xs-10 col-md-8 col-lg-4">
                        <img src="{{book.image.url}}" width="100%" height="100%">
                    </div>
                    <div class="col ">
                        <div class="card-body">
                            <h2 class="text-warning"><a href="{% url 'books:borrow' book.id %}"> {{ book }} </a> <br></h2>
                            <p class="text-responsive">{{ book.description }}</p> <br>
                            <div class="float-right">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="dropdown-divider"></div>
        {% endfor %}
    {% else %}
        <h1>Unfortunately the book you have searched for is unavailable!</h1>
    {% endif %}
{% endblock content %}